import { Form } from "@/components/CreateDeliveryRequest";
import { DeliveryRequestCreated } from "@/components/Notification";
import { Inter } from "@next/font/google";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Delivery Express</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container">
        <h1>Delivery Express</h1>

        <DeliveryRequestCreated />
        <Form />
      </main>
    </>
  );
}
