/**
 * Generated by @openapi-codegen
 *
 * @version 1.0
 */
import * as reactQuery from "@tanstack/react-query";
import {
  useDeliveryExpressApiContext,
  DeliveryExpressApiContext,
} from "./deliveryExpressApiContext";
import type * as Fetcher from "./deliveryExpressApiFetcher";
import { deliveryExpressApiFetch } from "./deliveryExpressApiFetcher";

export type QueryOperation = {
  path: string;
  operationId: never;
  variables: unknown;
};
