/**
 * Generated by @openapi-codegen
 *
 * @version 1.0
 */
export type Address = {
  street?: string | null;
  city?: string | null;
  state?: string | null;
  zipCode?: string | null;
  /**
   * @format int32
   */
  number?: number;
  complement?: string | null;
  neighborhood?: string | null;
};

export type CreateDeliveryRequest = {
  /**
   * @format int32
   */
  clientId?: number;
  address?: Address;
  items?: DeliveryItems[] | null;
};

export type CreateDeliveryRequestResponse = {
  /**
   * @format int32
   */
  id?: number;
};

export type DeliveryItems = {
  /**
   * @format int32
   */
  product?: number;
  /**
   * @format int32
   */
  quantity?: number;
};
